---
- hosts: tomcat_servers
  become: yes
  vars:
    java_version: java-11-openjdk
    tomcat_version: 9.0.50
    tomcat_download_url: https://downloads.apache.org/tomcat/tomcat-9/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz
    tomcat_install_dir: /opt/tomcat
    tomcat_user: tomcat
    tomcat_group: tomcat

  tasks:
  - name: Update all packages to the latest version
    dnf:
      name: "*"
      state: latest

  - name: Install required packages
    dnf:
      name:
        - "{{ java_version }}"
        - tar
      state: present

  - name: Create group tomcat
    group:
      name: "{{ tomcat_group }}"
      state: present

  - name: Create user tomcat
    user:
      name: "{{ tomcat_user }}"
      group: "{{ tomcat_group }}"
      home: "{{ tomcat_install_dir }}"
      shell: /sbin/nologin
      system: yes
      state: present

  - name: Download Tomcat
    get_url:
      url: "{{ tomcat_download_url }}"
      dest: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"

  - name: Create installation directory
    file:
      path: "{{ tomcat_install_dir }}"
      state: directory
      mode: '0755'
      owner: "{{ tomcat_user }}"
      group: "{{ tomcat_group }}"

  - name: Extract Tomcat tar.gz
    unarchive:
      src: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
      dest: "{{ tomcat_install_dir }}"
      remote_src: yes
      owner: "{{ tomcat_user }}"
      group: "{{ tomcat_group }}"
      creates: "{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}"

  - name: Set permissions on the installation directory
    file:
      path: "{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}"
      state: directory
      recurse: yes
      owner: "{{ tomcat_user }}"
      group: "{{ tomcat_group }}"
      mode: '0755'

  - name: Create symlink to latest Tomcat version
    file:
      src: "{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}"
      dest: "{{ tomcat_install_dir }}/latest"
      state: link

  - name: Install Tomcat service
    template:
      src: /path/to/tomcat.service.j2
      dest: /etc/systemd/system/tomcat.service
      mode: '0644'
    notify: restart tomcat

  handlers:
  - name: restart tomcat
    systemd:
      name: tomcat
      state: restarted
      enabled: yes
