---
- name: Verify application deployment
  hosts: all
  gather_facts: no
  tasks:
    - name: Load specification
      set_fact:
        spec: "{{ lookup('file', 'specifications.json') | from_json }}"

    - name: Verify endpoints
      uri:
        url: "{{ item.url }}"
        method: GET
        status_code: "{{ item.status }}"
      with_items: "{{ spec['endpoints'] }}"
      register: endpoint_results

    - name: Verify network configuration
      command: iptables -L
      register: network_config
      changed_when: false
      when: ansible_network_os is defined

    - name: Ensure allowed ports are open
      debug:
        msg: "Port {{ item }} is open"
      with_items: "{{ spec['network']['allowed_ports'] }}"

    - name: Check for restricted IPs
      shell: "grep '{{ item }}' /var/log/iptables.log"
      with_items: "{{ spec['network']['restricted_ips'] }}"
      register: ip_check

    - name: Verify servers and services
      shell: "systemctl is-active {{ item.service }}"
      register: service_status
      with_items: "{{ spec['servers'] }}"
      when: ansible_os_family == 'Linux'

    - name: Ensure service is running
      debug:
        msg: "Service {{ item.service }} on {{ item.host }} is {{ item.status }}"
      with_items: "{{ spec['servers'] }}"
